name: Ejecutar Bot Diario

on:
  schedule:
    - cron: '0 11 * * *'  # 11:00 UTC = 8:00 Argentina
  workflow_dispatch:  # Permite ejecutarlo manualmente

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install requests

      - name: Ejecutar bot
        run: python Bot_de_finanzas.py
